src/app/globals.css
src/app/page.tsx
src/components/elements/CategoryItem/CategoryItem.tsx
src/components/elements/CategoryItem/CategoryItem.type.tsx
src/components/layouts/Category/Category.tsx

- 카테고리 개별 요소 컴포넌트 작업
- 카테고리 전체 컴포넌트 작업
- 앱 라우팅 초기 화면에 컴포넌트 UI 반영
resolves #12

✨ feat: 카테고리 UI 컴포넌트 작업 완료

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement_request.md
.github/ISSUE_TEMPLATE/task.md

- '그외 할일' 이슈 템플릿 추가
- 이슈 템플릿 타입 작성
resolves #16

🐳 chore: Github 이슈 탬플릿 Type 지정

---

src/shared/data/categoryData.json

- 상품 분류용 카테고리 코드 구조화
- 속성 태그 코드 정의 (신상품, 인기상품 등)
resolves #31

📝 docs: 카테고리/태그/장바구니 상태 코드 정의 및 JSON 파일 추가

---

src/app/page.tsx
src/components/layouts/Header/SearchHeader.tsx

✨ feat: 검색 헤더 기능 추가

---

src/app/page.tsx
src/components/elements/CommonButton/CommonButton.tsx
src/components/elements/CommonButton/CommonButton.type.tsx

- 크기와 텍스트 내용에 따라 버튼을 생성할 수 있도록 컴포넌트를 만들었습니다.
-  피그마 시안에 있는 버튼 ( 장바구니 담기, 로그인, 자세히 보기 )의 UI를 완성했습니다.
resolves #43

 ✨feat: 공통 버튼 컴포넌트 UI 구현

---

src/app/(accounts)/(seller)/office/page.tsx
src/app/(accounts)/(user)/mypage/page.tsx
src/app/(accounts)/account/page.tsx
src/app/(accounts)/register/page.tsx
src/app/(exploring)/product/[type]/[category]/page.tsx
src/app/(exploring)/product/[type]/page.tsx
src/app/(exploring)/search/page.tsx

- 특정 페이지가 어떤 페이지인지 확인하기 위한 텍스트 추가
resolves #48

🐳 chore: 라우팅 폴더 구조 확인 및 컴포넌트 함수 내 텍스트 개선

---

public/svgs/arrow-right.svg
src/app/page.tsx
src/components/elements/Path/Path.tsx

- 사용자가 텍스트를 누르면 해당 path로 이동할 수 있도록 구현했습니다.
- CHECKLIST 확인해주시고 경로 수정이 필요한지 확인해주세요
resolves #62

 ✨feat : 상품 경로 컴포넌트 UI 구현

---

package-lock.json
package.json
src/app/(exploring)/product/[type]/[category]/[_id]/page.tsx
src/components/elements/BuyBoxForMobile/BuyBoxOption.tsx
src/components/elements/BuyBoxForMobile/BuyBoxOption.type.tsx
src/components/elements/BuyBoxForMobile/BuyBoxOptionExtraItem.tsx
src/components/elements/BuyBoxForMobile/BuyBoxOptionExtraItem.type.tsx
tailwind.config.js

- 상품 상세 페이지 내부에서 구매 버튼을 클릭하면 팝업되는 상품 타입별 컴포넌트 UI 제작
- date-fns, tailwind-scrollbar 라이브러리 설치
resolves #68

✨feat : 구매 버튼 모달 팝업 컴포넌트 UI 완성

---

src/components/layouts/Header/SearchHeader.tsx

🩹 fix: 테스트용 코드 삭제

---

src/components/elements/CategoryItem/CategoryItem.tsx
src/shared/api/dbinit/team/data.js

- CategoryItem.ts 링크 패딩을 3 -> 2 로 수정
resolves #82

📝 docs: DB문서 수정 및 스타일 수정

---

src/app/(accounts)/login/page.tsx
src/components/elements/BuyBoxForMobile/BuyBoxOption.tsx
src/components/layouts/SortBar/Sortbar.tsx

배포 테스트용 배포

---

src/app/(accounts)/login/page.tsx
src/app/(accounts)/register/page.tsx
src/app/(accounts)/register/seller/page.tsx
src/app/(accounts)/register/user/page.tsx
src/components/elements/CheckButton/CheckButton.tsx
src/components/elements/CommonButton/CommonButton.tsx
src/components/elements/CommonButton/CommonButton.type.tsx
src/components/elements/LoginItem/LoginInput.tsx
src/components/elements/LoginItem/LoginInput.type.tsx
src/components/elements/ProductLink/ProductLink.tsx
src/components/elements/ProductLink/ProductLink.type.tsx

- 회원가입 선택 페이지 UI 구현
- 회원가입 페이지 UI 구현
resolves #90

 ✨feat : 회원가입 페이지 UI 구현

---

src/app/(exploring)/product/[type]/page.tsx
src/app/(exploring)/search/result/page.tsx
src/app/globals.css
src/app/page.tsx
src/components/elements/BuyBoxForMobile/BuyBoxOption.tsx
src/components/elements/CategoryItem/CategoryItem.tsx
src/components/elements/InteractionButton/InteractionButton.tsx
src/components/layouts/Header/CategoryHeader.tsx

- 상품 검색 결과 및 탐색 목록 페이지 UI 스타일링 코드 수정
- 로그인 관련 테스트 코드 삭제
- Heading 레벨 코드 수정
resolves #111

 ♻️ refactor: 상품 검색 결과 및 상품 탐색 목록 페이지 개선

---

src/app/(exploring)/search/page.tsx
src/app/(exploring)/search/result/page.tsx
src/app/page.tsx
src/components/layouts/Header/CategoryHeader.tsx

- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #123

🚑 hotfix: 빌드 오류건 수정

---

src/app/(exploring)/product/[type]/ProductListByType.type.ts
src/app/(exploring)/product/[type]/not-found.tsx
src/app/(exploring)/product/[type]/page.tsx

- /product/[type] 정적 페이지 타입 설정
- 해당 경로 외 페이지 접근시 not-found.tsx 로 이동하도록 구현
resolves #120

✨ feat: /product/[type] 동적 라우팅 경로 추가

---

src/app/(accounts)/login/page.tsx
src/components/elements/CommonButton/CommonButton.tsx
src/components/elements/CommonButton/CommonButton.type.tsx
src/components/elements/LoginItem/LoginInput.tsx
src/components/layouts/Login/LoginForm.tsx

- 비밀번호 텍스트가 보이지 않았던 이유
- 비밀번호 입력 시 마스킹 처리된 ●●●●● 문자가 보여야 하지만 현재 사용 중인 폰트에서 해당 문자를 지원하지 않아 텍스트가 표시되지 않습니다.
- 그래서 loginInput 리팩토링했습니다. ( + 글꼴 )
- 빌드 오류 수정
- 보기 숨기기 기능 추가
- 로그인 정보 일치 시 루트(/)로 이동, 불일치 시 에러 메시지와 로그인 페이지 리로드 기능 추가 
resolves #118

 ✨feat : 로그인 기능 구현 , 코드 리팩토링

---

src/app/(exploring)/product/[type]/page.tsx
src/app/(exploring)/search/page.tsx
src/app/(exploring)/search/result/[_id]/detail/page.tsx
src/app/(exploring)/search/result/[_id]/layout.tsx
src/app/(exploring)/search/result/page.tsx
src/components/elements/InteractionButton/InteractionButton.tsx
src/components/elements/LoginItem/LoginInput.tsx
src/components/elements/ProductItem/Item/CropItem.tsx
src/components/layouts/Header/CategoryHeader.tsx
src/components/layouts/Header/types/Header.type.ts

- usePathname, useSearchParams 훅 사용
- 해당 경로를 확인하여 헤더의 텍스트를 동적으로 변경
- 상품 상세 페이지에서는 상품명으로 삽입되도록 동작
resolves #130

✨ feat: CategoryHeader 기능 완성

---

src/app/(exploring)/product/[type]/page.tsx
src/app/(exploring)/search/result/[_id]/qna/page.tsx
src/app/(exploring)/search/result/[_id]/review/page.tsx
src/app/(exploring)/search/result/page.tsx
src/components/elements/InteractionButton/InteractionButton.tsx
src/components/elements/LinkIcon/LinkIcon.tsx
src/components/elements/ProductItem/Item/CropItem.tsx
src/components/elements/ProductItem/Item/ExperienceItem.tsx
src/components/elements/ProductItem/Item/GardenItem.tsx
src/components/elements/ProductItem/Item/Item.type.tsx
src/components/elements/ProductItem/List/ProductItemList.tsx
src/components/layouts/SortBar/Sortbar.tsx
src/shared/data/functions/bookmarks.ts
src/shared/store/bookmarkStore.ts
src/shared/types/bookmarkt.ts
src/shared/types/product.ts

-북마크 기능 관련은 추가해야합니다.
resolves #113
resolves #116

✨ feat: 상품 관련 페이지 DB 기능 연결 

---

src/app/(accounts)/register/seller/page.tsx
src/app/(accounts)/register/user/page.tsx

- user 회원가입 기능 추가
- seller 회원가입 기능 추가
resolves #117

 ✨feat : 회원가입 기능 구현

---

src/app/(accounts)/(user)/mypage/cart/page.tsx
src/components/elements/BuyModal/BuyModal.tsx
src/components/elements/DeleteButton/DeleteButton.tsx
src/components/elements/InputButtonForMypage/InputButtonForMypage.tsx
src/components/elements/InputButtonForMypage/InputButtonForMypage.type.ts
src/components/elements/cardItem/cardItem.tsx
src/components/layouts/Header/CategoryHeader.tsx
src/features/cartClientControl/cartClientControl.tsx
src/shared/data/actions/cart.ts
src/shared/data/functions/cart.ts
src/shared/types/cart.ts

- 장바구니에서 여러 상품을 선택해서 주문할 경우 주문페이지 에서 한 상품만 나오는 문제 발견 
- 장바구니에서 주문 버튼 누를시 주문 페이지로 가는 로직 필요
현재는 바로 주문이 되는 로직으로 구현되어 있음.
-장바구니 담는 경우 장바구니로 이동할 건지 묻는 창 제안
resolves #141

✨ feat: 장바구니 기능 구현 완료

---

src/components/elements/HamburgerIcon/HamburgerIcon.tsx

🩹 fix: 햄버거 버튼 로그인 상태에 따른 페이지 라우팅 경로 수정건 삭제

---

src/app/(accounts)/register/seller/registerForm.tsx
src/app/(accounts)/register/user/page.tsx
src/app/(accounts)/register/user/registerForm.tsx
src/components/elements/LoginItem/LoginInput.tsx

- 주소 검색 버튼 type "submit" -> "button"으로 수정했습니다.
-> 주소 검색 버튼 클릭 시 의도치 않게 폼이 제출되던 문제를 해결했습니다.
-  비밀번호가 빈 상태일 때, ‘보기’ 및 ‘숨기기’ 옵션 안보이게 수정했습니다.
- 회원가입 폼 내 오타 수정했습니다.
- 회원가입 폼 내 체크 된 상태 수정했습니다.
- 리팩토링 리스트 참고해서 코드를 개선했습니다.  https://www.notion.so/7-24-23973873401a8101b7a7cb09db86a881
resolves #

 🚑 Hotfix : 로그인 페이지/회원가입 페이지 개선

---

src/components/elements/OrderItem/OrderItem.tsx

- [x ] 버그 수정
- 다른 종류의 상품을 함께 주문했을때 한 상품만 주문 페이지에서 렌더링 되는 오류 해결 했습니다.'
- 함께 주문한 상품은 주문 state를 하나로 관리되고 있어서 묶어서 렌더링 되게 했습니다.
resolves #154

✨ feat: 주문 페이지 렌더링 오류 해결 완료

---

package-lock.json
package.json
src/app/layout.tsx
src/components/elements/BuyBoxForMobile/BuyBoxOption.tsx
src/components/elements/BuyBoxForMobile/BuyBoxOption.type.tsx
src/components/elements/BuyModal/BuyModal.tsx
src/components/elements/BuyModal/BuyModal.type.ts
src/components/elements/ToasterWrapper/ToastWrapper.tsx
src/components/layouts/Modal/CartSuccessModal.tsx
src/features/buyModal/buyModalAction.tsx
src/features/cartClientControl/cartClientControl.tsx
src/features/cartItemCountIcon/CartItemCountIcon.tsx

✨ feat: 장바구니 담기 배너추가, 토스트 라이브러리 추가

---

src/components/elements/LoginItem/LoginInput.tsx

- 회원가입 이메일 입력창 UI 수정
- 직접 입력하기 기능 추가했습니다.
resolves #180

♻️ refactor: 2차 배포건 추가 리팩토링

---

src/app/(exploring)/search/result/[_id]/loading.tsx
src/app/(exploring)/search/result/[_id]/qna/page.tsx
src/app/(exploring)/search/result/[_id]/review/page.tsx
src/components/elements/OrderItem/OrderItem.tsx
src/components/elements/OrderItem/OrderItem.type.ts
src/components/elements/QnaItem/QnaItem.tsx
src/components/layouts/SortBar/Sortbar.type.ts
src/features/orderClientControl/orderClientControl.tsx
src/features/qnaClientControl/productCateory.tsx
src/features/qnaClientControl/qnaClientControl.tsx
src/features/reviewClientControl/reviewClientControl.tsx
src/shared/data/actions/file.ts
src/shared/data/actions/post.ts
src/shared/data/actions/replies.ts
src/shared/data/functions/post.ts
src/shared/types/file.ts
src/shared/types/order.ts
src/shared/types/post.ts
src/shared/types/qna.ts

- 사진 첨부해서 등록을 정상작동하며, 파일로 저장된 사진을 읽어오는 기능 테스트 중 입니다.
- 글을 작성후 리로딩 과정이 없어서 새로고침을 해야 업데이트가 되는 현상 존재합니다.
- 현재 사진 첨부는 한 개로 제한되어 있습니다.
resolves #177
resolves #182

♻️ refactor: 2차 배포건 리팩토링 및 리뷰,qna 작성 기능 완료 (사진 첨부는 테스트중)

---

src/app/(accounts)/(seller)/office/analytics/page.tsx
src/app/(accounts)/(seller)/office/orders/page.tsx
src/app/(accounts)/(seller)/office/products/edit/page.tsx
src/app/(accounts)/(seller)/office/products/new/page.tsx
src/app/(accounts)/(seller)/office/products/select/new/page.tsx
src/app/(accounts)/(seller)/office/products/select/page.tsx
src/app/(accounts)/register/seller/registerForm.tsx
src/app/(exploring)/search/page.tsx
src/app/(exploring)/search/result/page.tsx
src/app/board/review/edit/page.tsx
src/app/board/review/new/page.tsx
src/app/board/review/page.tsx
src/components/elements/HamburgerIcon/HamburgerIcon.tsx
src/components/elements/LoginItem/LoginInput.tsx
src/components/elements/RelatedKeywordItem/RelatedKeywordItem.type.tsx
src/components/elements/SearchForm/SearchForm.tsx
src/components/elements/TopRatedItem/TopRatedItem.tsx
src/features/productListFilteredKeyword/productListFilteredKeyword.tsx
src/shared/store/keywordStore.ts
src/shared/types/product.ts
src/shared/types/user.ts

- 비로그인 상태인 경우, 햄버거 버튼에 '로그인' 표시 기능 추가
- 인기 텃밭 순위 로직 수정
- 판매자 회원가입 시, DB 반영이 안되는 오류 수정
- 검색 기능 중간 저장 : server -> client 컴포넌트 간 직렬화 이슈 해결 필요 (중간 DB 로딩 및 필터링 기능 정상 작동 확인 완료)
- 라우팅 구조 업데이트
resolves #186

♻️ refactor: 2차 배포건 리팩토링 및 검색 기능 개발(진행 중)

---

src/app/layout.tsx
src/components/layouts/Login/LoginForm.tsx
src/features/initAuthStore/initAuthStore.tsx
src/shared/store/authStore.ts

자동 로그인 기능을 상세 구현했습니다.
- 자동 로그인 시 로컬 스토리지에 저장 ( 만료일 : 하루 )
- 일반 로그인 시 세션 스토리지에 저장
- 로그아웃 시 localStorage 값이 삭제되지 않던 버그를 수정했습니다.
resolves #192

♻️ refactor : 자동 로그인 기능 상세 구현

---

src/app/(exploring)/search/page.tsx
src/app/(exploring)/search/result/page.tsx
src/components/elements/ProductItem/List/ProductItemList.tsx
src/components/elements/SearchForm/SearchForm.tsx
src/features/goBackIcon/goBackIcon.tsx
src/features/productListFilteredKeyword/productListFilteredKeyword.tsx

- 뒤로 가기 기능 개선(하위 페이지 1개, 2개인 경우 라우팅 방식 개선)
- SearchHeader 에서 검색어 입력 시, 검색 결과 페이지에서 DB 가 반영되는 로직 완성
- 필터링 기능으로 타입에 따른 검색 결과 필터링 기능 완성
resolves #191

✨ feat: 검색 기능 및 필터링 기능 구현 완료(정렬 관련 컴포넌트 기능 개발 필요)

---

src/app/(exploring)/search/result/[_id]/detail/page.tsx
src/components/elements/RelatedKeywordItem/RelatedKeywordItem.tsx
src/components/elements/SearchForm/SearchForm.tsx
src/features/productListFilteredKeyword/productListFilteredKeyword.tsx

♻️ refactor : 검색어 자동 완성 리팩토링

---

src/components/layouts/Login/BackOfficeSectionDependsOnLoginStatus.tsx
src/shared/data/actions/order.ts
src/shared/data/functions/order.ts
src/shared/data/functions/product.ts

✨ feat: 판매자 관리페이지(메인) DB 업데이트 기능 구현 완료

---

src/app/(accounts)/(seller)/office/orders/page.tsx
src/components/elements/OrderItem/OrderItem.tsx
src/components/elements/OrderItem/OrderItemForSeller.tsx
src/components/elements/OrderOption/OrderOption.tsx
src/features/cartClientControl/cartClientControl.tsx
src/features/officeOrderClientControl/officeOrderClientControl.tsx

✨ feat:  판매자 관리페이지 중 주문내역 페이지 DB 업데이트 및 필터링 기능 구현 완료

---

src/app/(accounts)/(seller)/office/products/select/editor/crop/page.tsx
src/app/(accounts)/(seller)/office/products/select/editor/experience/page.tsx
src/app/(accounts)/(seller)/office/products/select/editor/gardening/page.tsx
src/components/elements/BuyModal/BuyModal.tsx
src/components/elements/LoginItem/Input.tsx
src/components/elements/OrderOption/SellerProductEditOption.tsx
src/components/elements/PickListItem/PickListItem.tsx
src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
src/components/elements/ProductItem/List/ProductItemList.tsx
src/features/ProductPostClientControl/CropProductPostClientControl.tsx
src/features/ProductPostClientControl/ExperienceProductPostClientControl.tsx
src/features/ProductPostClientControl/GardeningProductPostClientControl.tsx
src/shared/data/actions/product.ts
src/shared/types/product.ts

✨ feat: 상품 등록 기능 구현 완료

---

src/app/(accounts)/(seller)/office/qnas/page.tsx
src/components/elements/OrderOption/sellerQnaOption.tsx
src/components/elements/QnaItem/SellerQnaItem.tsx
src/components/layouts/Login/BackOfficeSectionDependsOnLoginStatus.tsx
src/features/sellerQnaPageClientControl/sellerQnaPageClientControl.tsx
src/shared/types/post.ts

✨ feat: 판매자 Qna 페이지 구현 완료

---

src/components/elements/GardenItemForMyGarden/GardenItemListForMyGarden.tsx
src/components/elements/ProgressBar/ProgressBar.tsx
src/components/layouts/Footer/Footer.tsx

- 푸터 SNS 이미지 오류건 삭제(X / 구 트위터)
- 텃밭 히스토리 개별 상품 Key Props 를 Index 로 변경
- 텃밭 히스토리 상세 페이지에서 튀어나가는 현상 수정

🐛 bugfix: 빌드 오류 및 기능 오류건 수정

---

src/app/(accounts)/register/seller/registerForm.tsx
src/components/elements/AccoutItem/AccountForm.tsx
src/components/elements/AccoutItem/AccountItem.tsx
src/components/elements/LoginItem/LoginInput.tsx
src/components/elements/LoginItem/LoginInput.type.tsx
src/components/elements/OrderItem/OrderItem.tsx
src/components/elements/ProductItem/Badge/Badge.tsx
src/components/elements/ProductItem/Item/CropItem.tsx
src/components/elements/ProductItem/Item/GardenItem.tsx
src/features/orderClientControl/orderClientControl.tsx
src/features/productListClientControl/productListClientControl.tsx
src/features/productListFilteredKeyword/productListFilteredKeyword.tsx

- 판매자 회원가입시 대표 전화 정규표현식 수정
- 이미지 카테고리 쿼리스트링 반영 기능 추가
- 판매자 정산 페이지 완성
- 마이페이지 주문/배송 내역에서 상품의 리뷰를 작성하면 상태 변경에 따라 리렌더링되도록 수정
- 마이페이지 주문/배송 내역에서 개별 아이템 클릭 시 해당 상품의 상세페이지로 이동하도록 수정
- 검색 결과 목록에서 북마크 기능이 동작하지 않는 오류
- 상품 목록 수가 적을 때 그리드가 어색하게 나타나는 문제
- 뱃지 색 오류
resolves #256 #238

♻️ refactor: 3차 빌드 오류 내용 중 일부 해결, 수정 및 개선

---

src/app/(accounts)/(seller)/office/products/select/page.tsx
src/app/(accounts)/register/page.tsx
src/app/page.tsx
src/components/elements/BannerItem/SlideBannerItem.tsx
src/components/elements/BannerItem/SlideBannerItem.type.tsx
src/components/elements/CategoryItem/CategoryItem.tsx
src/components/elements/LoginItem/LoginInput.tsx
src/components/elements/NavigationItem/NavigationItem.tsx
src/components/elements/NavigationItem/NavigationItem.type.tsx
src/components/elements/RegisterItem/RegisterCardItem.tsx
src/components/layouts/Banner/SlideBanner.tsx
src/components/layouts/Login/LoginForm.tsx
src/components/layouts/Navigation/Navigation.tsx

- Navigation 을 클릭하면 메인 페이지 내 추천 카테고리로 이동하도록 기능 구현
- #id 로 이동하되, absolute 헤더로 스크롤 이동 시 위치가 어색한 것을 scroll-mt-... 스타일로 조정
- Navigation 텍스트 및 추천 카테고리 텍스트 수정
- 이미지 슬라이드 배너 클릭 시, 해당 이미지의 원본 DB 내 keyword 를 추출하여 해당 키워드의 검색 결과로 이동하도록 기능 구현
- 디폴트 이메일/비밀번호 수정(seller1)
- 상품 등록 페이지 중 상품 선택 영역 스타일링 수정
- (개선 필요) 세부적인 큐레이션 콘텐츠를 추가하거나, 리뷰 모아보기 등 별도의 콘텐츠 삽입하면 좋을 것
resolves #255

✨ feat: Navigation 기능 구현, SlideBanner 링크 기능 추가, 기타 스타일링 수정

---

src/components/elements/ReviewItem/ReviewItem.tsx
src/components/layouts/Modal/OrderSucessModal.tsx
src/features/ProductPostClientControl/GardeningProductPostClientControl.tsx
src/features/cartClientControl/cartClientControl.tsx

♻️ refactor: 3차 배포 리팩토링 (사진 업로드 오류 문제 해결)

---

src/app/page.tsx
src/components/elements/ReviewItem/ReviewItem.tsx
src/components/elements/ReviewItem/ReviewItemCard.tsx
src/components/elements/boardItem/noticeItem.tsx
src/components/layouts/Navigation/Navigation.tsx
src/shared/types/review.ts

- 첨부된 리뷰 사진이 없을경우 상품 사진이 나오도록 설정해두었는데 현재 등록된 사진의 이미지 형식이 맞지 않아 오류가 나고 있는 상황입니다. 이 점은 상품 사진을 넣는 과정에서 수정할 예정입니다.
resolves #269

✨ feat: 메인 페이지 요소 추가 완료

---

src/app/(exploring)/search/result/[_id]/detail/page.tsx
src/components/elements/OrderItem/OrderItem.tsx
src/components/elements/OrderItem/OrderItemForSeller.tsx
src/components/elements/PickListItem/PickListItem.tsx
src/components/elements/cardItem/cardItem.tsx
src/shared/api/dbinit/team/data.json
src/shared/types/cart.ts

- 모든 페이지에서 변경된 이미지가 렌더링 되도록 수정했습니다.
resolves #284

✨ feat: 이미지 경로 수정

---

src/app/page.tsx

- 메인 배포건으로 주석 수정만 먼저 올릴게요!
resolves #

🩹 fix: 주석 텍스트 주석 처리

---

src/components/elements/BannerItem/SlideBannerItem.tsx

🩹 fix: 빌드 에러 코드 삭제

---

src/components/elements/BannerItem/SlideBannerItem.tsx

- video 태그 관련 속성 추가
resolves #300

🩹 fix: 모바일에서 동영상 배너 이슈 해결

---

src/app/(accounts)/(seller)/office/layout.tsx
src/app/(accounts)/(user)/mypage/layout.tsx
src/components/elements/ReviewItem/ReviewItem.tsx
src/features/redirectRouteToLogin/RedirectRouteToLogin.tsx
src/features/redirectRouteToMypage/RedirectRouteToMypage.tsx

- 로그인 상태를 검증하여 로그인되지 않은 경우 /mypage (하위 모든 페이지) URL 입력시 로그인 페이지로 강제 라우팅
- ReviewItem 빌드 오류 수정

🚑 hotfix: 로그인하지 않고 마이페이지 URL 직접 입력하면 이동해지는 오류 수정

---

src/components/elements/ProductItem/List/ProductItemListForSeller.tsx

- 수정 버튼 클릭 시 경로 연결
- 접근성 개선을 위해 aria-label 수정
-  연결된 경로가 맞는지 확인 부탁드립니다.
-  수정 버튼 클릭 시 데이터를 받은 후 수정 기능이 정상 작동하도록 구현 부탁드립니다 🙏
resolves #320

 🩹fix :  상품 관리 페이지 수정 버튼 경로 연결 및 aria-label 수정

---

src/app/(accounts)/register/user/registerForm.tsx
src/components/elements/LoginItem/LoginInput.tsx

 🚑 hotfix: 회원가입 생일 유효성 검사 추가

---

src/shared/api/dbinit/team/data.json

- json 데이터 하나 추가했습니다. 오류가 있어서요!
resolves #

🩹 fix: data.json 적상추 텃밭 상품 Period 추가

---

src/app/(accounts)/(seller)/office/products/select/editor/crop/page.tsx
src/app/(accounts)/(seller)/office/products/select/editor/experience/page.tsx
src/app/(accounts)/(seller)/office/products/select/editor/gardening/page.tsx

🩹 fix: Suspense 추가 (빌드 에러)

---

src/app/(accounts)/register/user/registerForm.tsx

🚑 hotfix: 회원가입 주소 유효성 검사 추가
